name: mangs/simple-release-notes-action
author: Eric L. Goldstein
description: GitHub Action that auto-publishes release notes using a very simple-to-follow set of rules
inputs:
  changelog_path:
    default: ./CHANGELOG.md
    description: Path to the target changelog file
    required: false
  github_token:
    description: GitHub authentication token used to authenticate on behalf of GitHub Actions
    required: true
  packagejson_path:
    default: ./package.json
    description: Path to the target package.json file
    required: false
  should_auto_update_major_tag:
    default: true
    description: Auto-update the major tag version of your repository when a new release gets published or create it if it doesn't exist. For example, when publishing version 2.3.4, major tag v2 will get updated to HEAD.
    required: false
  tag_override:
    description: String to enforce an exact tag version; overrides default behavior
    required: false
  tag_prefix:
    default: v
    description: Prefix to create a tag by combining this and the target version number; this is default behavior
    required: false
runs:
  using: node20
  main: ./src/publishReleaseNotes.mjs
